name: Backend CI

on:
  pull_request:
    branches: [main]
    paths: 'backend/**'
  push:
    branches: [main]
    paths: 'backend/**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run backend tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          scripts/test.sh
